defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

pull_request_rules:
  - name: backport patches to v22 branch
    conditions:
      - base=osmo/v0.47.5
      - label=A:backport/v22
    actions:
      backport:
        branches:
          - osmo-v22/v0.47.5
  - name: backport patches to v23 branch
    conditions:
      - base=osmo/v0.47.5
      - label=A:backport/v23
    actions:
      backport:
        branches:
          - osmo-v23/v0.47.5
          - osmo-v23/v0.47.5-iavl-v1
  - name: backport patches to v24 branch
    conditions:
      - base=osmo/v0.47.5
      - label=A:backport/v24
    actions:
      backport:
        branches:
          - osmo-v24/v0.47.5
  - name: backport patches to v25 branch
    conditions:
      - base=osmo/v0.47.5
      - label=A:backport/v25
    actions:
      backport:
        branches:
          - osmo-v25/v0.47.5
  - name: backport patches to sdk v50 branch
    conditions:
      - base=osmo/v0.47.5
      - label=A:backport/sdk-v50
    actions:
      backport:
        branches:
          - osmo/v0.50.x
