queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>1"

pull_request_rules:
  - name: automerge to master with label automerge and branch protection passing
    conditions:
      - "#approved-reviews-by>1"
      - base=v0.45.0x-osmo-v7
      - label=automerge
    actions:
      queue:
        name: default
        method: squash
        commit_message_template: |
           {{ title }} (#{{ number }})
           {{ body }}
  - name: backport patches to v0.42.x branch
    conditions:
      - base=master
      - label=backport/0.42.x (Stargate)
    actions:
      backport:
        branches:
          - release/v0.42.x
  - name: backport patches to v8 branch
    conditions:
      - base=master
      - label=backport/v8
    actions:
      backport:
        branches:
          - v0.45.0x-osmo-v8
